### PR TITLE
Depend on SafeSemaphore 0.10

### PR DESCRIPTION
**Pull request by 3noch**
For #3. My editor removed trailing whitespace. If you're not a fan, say the word and I'll rebase those changes away.

### CODE REVIEW

**Comment by 3noch** [comment]
@nikita-volkov I'm not sure what I broke!

**Comment by nikita-volkov** [comment]
It's okay. Some dependencies got outdated since the last Travis execution. I'll revise some time soon.

**Comment by 3noch** [comment]
@nikita-volkov Give me a few pointers and I'll try a stab at it.

**Comment by 3noch** [comment]
@nikita-volkov How did it go? I noticed you had to allow failures on GHC 7.8.4. Why is that?

**Comment by nikita-volkov** [comment]
They were initially allowed, I just restored them. 

The problem is that "graph-db" currently depends on the "layers" project, which unfortunately the community didn't catch up and it stopped evolving. It's "layers" that doesn't support GHC 7.8. So we need to get rid of the dependency on it updating the code accordingly.

**Comment by 3noch** [comment]
`layers` appears to be a pretty ambitious project (but with good aspirations). It's a shame it's not being evolved. What's the reason for that?

**Comment by 3noch** [comment]
Instead of replacing it, could it be updated to support 7.8.4. It seems there is an [issue](https://github.com/duairc/layers/issues/8) for that already but the author is not responsive.

**Comment by nikita-volkov** [comment]
Since the author does not react on issues for months, and taking the project over is neither an option for me (I'm speaking for myself), it's probably best to not depend on such a project. I wouldn't advise you to take that project over either, since it's a huge conceptual work, and as I've seen the community is not keen to make a switch to it. I actually was trying to promote it some time ago, but it just didn't work.

That said, I hope the author of the project is fine, 'cause there hasn't been any activity on [his Reddit account](http://www.reddit.com/user/duairc) for a while either.

**Comment by 3noch** [comment]
Ah, I see your [post](http://www.reddit.com/r/haskell/comments/1xnmiv/monad_layers_an_alternative_to_transformers/). You're right. The author's comment about "my mental health" is concerning. I really hope he is ok.

You'll notice that the hackage version is `0.1` but the GitHub code has a version of `1.0`. It might be worth trying to use the one on GitHub.

**Comment by 3noch** [comment]
An attempt at resurrection: http://www.reddit.com/r/haskell/comments/2ucazk/what_ever_happened_to_layers_package/

**Comment by 3noch** [comment]
@nikita-volkov Have you looked at the recently announced [monad-levels](https://github.com/ivan-m/monad-levels)?

**Comment by nikita-volkov** [comment]
Just took a basic look. Actually lately I have discovered myself using only the "transformers" library and doing explicit lifting, and introducing alias functions when there's too many levels. I have a feeling that this approach results in a more readable code. So I guess this problem does not trouble me lately in general.

**Comment by 3noch** [comment]
That seems to be what @ekmett was [getting at](http://www.reddit.com/r/haskell/comments/2ucazk/what_ever_happened_to_layers_package/co7sr3d).

**Comment by 3noch** [comment]
@nikita-volkov I think the only offending dependency for `layers` is [`cereal-plus 0.3.3`](http://hackage.haskell.org/package/cereal-plus-0.3.3).

**Pull request merged**
