### PR TITLE
Update dependencies to support GHC 7.8

### PR DESCRIPTION
**Pull request by 3noch**

### CODE REVIEW

**Comment by 3noch** [comment]
@nikita-volkov It appears that the `th-instance-reification` is our remaining problem.

**Comment by 3noch** [comment]
See https://github.com/nikita-volkov/th-instance-reification/issues/2 and https://github.com/nikita-volkov/QuickCheck-GenT/issues/1.

**Comment by nikita-volkov** [comment]
Sorry. Didn't notice this PR previously. It's merged now.

Don't hesitate to ping me if it ever happens again.

**Comment by 3noch** [comment]
@nikita-volkov Thanks for merging. I forgot all about it! I'll ping next time if needed.

**Pull request merged**
